version: '2'

services: 
  gitlab:                                                      # nom du service
    image: gitlab/gitlab-ce:8.9.6-ce.0                         # nom de l'image
    restart: always                                            # si le container crash, qu'il redémarre automatiquement
    hostname: '0.0.0.0'
    environment:
       GITLAB_OMNIBUS_CONFIG: |
       # external_url 'https://gitlab.example.com'
       # Add any other gitlab.rb configuration here, each on its own line
    ports:                                                     # exposition des ports
       - "80:80"
       - "443:443"
       - "2222:22"                                             # serveur ssh mapé à ce port
    volumes:                                                   # les volumes
    - /opt/gitlab/config:/etc/gitlab
    - /opt/gitlab/logs:/var/log/gitlab
    - /opt/gitlab/data:/var/opt/gitlab
